#define MATRIX_WIDTH 10
#define MATRIX_HEIGHT 20
#define TILE_SIZE 36

#define WINDOW_WIDTH 760 
#define WINDOW_HEIGHT 720

#define TETRIS_MAP_WIDTH 360
#define TETRIS_MAP_HEIGHT 720

#define TETRIS_MAP_INIT_X 200
#define TETRIS_MAP_INIT_Y 0

#define TETRIS_MAP_MARGIN 36
#define TETRIMINO_QUEUE_MARGIN 120

#define LOCK_DOWN_TIME 500 // in ms
#define VIRTUAL_BAG {'I', 'O', 'T', 'L', 'J', 'Z', 'S'}
